/* Generated By:JavaCC: Do not edit this line. SqlParserConstants.java */
package com.github.tycrelic.sqldisadvantage.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LPAREN = 7;
  /** RegularExpression Id. */
  int SELECT = 8;
  /** RegularExpression Id. */
  int CALL = 9;
  /** RegularExpression Id. */
  int ROLE = 10;
  /** RegularExpression Id. */
  int TRANSACTION = 11;
  /** RegularExpression Id. */
  int NEW_VALUE = 12;
  /** RegularExpression Id. */
  int CMD_NEW_LINE = 13;
  /** RegularExpression Id. */
  int EQUAL = 14;
  /** RegularExpression Id. */
  int AT_SIGN = 15;
  /** RegularExpression Id. */
  int DOUBLE_AT_SIGN = 16;
  /** RegularExpression Id. */
  int SLASH = 17;
  /** RegularExpression Id. */
  int ACCEPT = 18;
  /** RegularExpression Id. */
  int APPEND = 19;
  /** RegularExpression Id. */
  int ARCHIVE = 20;
  /** RegularExpression Id. */
  int ATTRIBUTE = 21;
  /** RegularExpression Id. */
  int BREAK = 22;
  /** RegularExpression Id. */
  int BTITLE = 23;
  /** RegularExpression Id. */
  int CHANGE = 24;
  /** RegularExpression Id. */
  int CLEAR = 25;
  /** RegularExpression Id. */
  int COLUMN = 26;
  /** RegularExpression Id. */
  int COMPUTE = 27;
  /** RegularExpression Id. */
  int CONNECT = 28;
  /** RegularExpression Id. */
  int COPY = 29;
  /** RegularExpression Id. */
  int DEFINE = 30;
  /** RegularExpression Id. */
  int DEL = 31;
  /** RegularExpression Id. */
  int DESCRIBE = 32;
  /** RegularExpression Id. */
  int DISCONNECT = 33;
  /** RegularExpression Id. */
  int EDIT = 34;
  /** RegularExpression Id. */
  int EXECUTE = 35;
  /** RegularExpression Id. */
  int EXIT = 36;
  /** RegularExpression Id. */
  int GET = 37;
  /** RegularExpression Id. */
  int HELP = 38;
  /** RegularExpression Id. */
  int HOST = 39;
  /** RegularExpression Id. */
  int INPUT = 40;
  /** RegularExpression Id. */
  int LIST = 41;
  /** RegularExpression Id. */
  int PASSWORD = 42;
  /** RegularExpression Id. */
  int PAUSE = 43;
  /** RegularExpression Id. */
  int PRINT = 44;
  /** RegularExpression Id. */
  int PROMPT = 45;
  /** RegularExpression Id. */
  int RECOVER = 46;
  /** RegularExpression Id. */
  int REMARK = 47;
  /** RegularExpression Id. */
  int REPFOOTER = 48;
  /** RegularExpression Id. */
  int REPHEADER = 49;
  /** RegularExpression Id. */
  int RUN = 50;
  /** RegularExpression Id. */
  int SAVE = 51;
  /** RegularExpression Id. */
  int SET = 52;
  /** RegularExpression Id. */
  int SHOW = 53;
  /** RegularExpression Id. */
  int SHUTDOWN = 54;
  /** RegularExpression Id. */
  int SPOOL = 55;
  /** RegularExpression Id. */
  int START = 56;
  /** RegularExpression Id. */
  int STARTUP = 57;
  /** RegularExpression Id. */
  int STORE = 58;
  /** RegularExpression Id. */
  int TIMING = 59;
  /** RegularExpression Id. */
  int TTITLE = 60;
  /** RegularExpression Id. */
  int UNDEFINE = 61;
  /** RegularExpression Id. */
  int VARIABLE = 62;
  /** RegularExpression Id. */
  int WHENEVER = 63;
  /** RegularExpression Id. */
  int XQUERY = 64;
  /** RegularExpression Id. */
  int CREATE = 65;
  /** RegularExpression Id. */
  int DELETE = 66;
  /** RegularExpression Id. */
  int DROP = 67;
  /** RegularExpression Id. */
  int INSERT = 68;
  /** RegularExpression Id. */
  int REPLACE = 69;
  /** RegularExpression Id. */
  int TRUNCATE = 70;
  /** RegularExpression Id. */
  int UPDATE = 71;
  /** RegularExpression Id. */
  int SET_APPINFO = 72;
  /** RegularExpression Id. */
  int SET_ARRAYSIZE = 73;
  /** RegularExpression Id. */
  int SET_AUTOCOMMIT = 74;
  /** RegularExpression Id. */
  int SET_AUTOPRINT = 75;
  /** RegularExpression Id. */
  int SET_AUTORECOVERY = 76;
  /** RegularExpression Id. */
  int SET_AUTOTRACE = 77;
  /** RegularExpression Id. */
  int SET_BLOCKTERMINATOR = 78;
  /** RegularExpression Id. */
  int SET_CMDSEP = 79;
  /** RegularExpression Id. */
  int SET_COLSEP = 80;
  /** RegularExpression Id. */
  int SET_CONCAT = 81;
  /** RegularExpression Id. */
  int SET_COPYCOMMIT = 82;
  /** RegularExpression Id. */
  int SET_COPYTYPECHECK = 83;
  /** RegularExpression Id. */
  int SET_DEFINE = 84;
  /** RegularExpression Id. */
  int SET_DESCRIBE = 85;
  /** RegularExpression Id. */
  int SET_ECHO = 86;
  /** RegularExpression Id. */
  int SET_EDITFILE = 87;
  /** RegularExpression Id. */
  int SET_EMBEDDED = 88;
  /** RegularExpression Id. */
  int SET_ERRORLOGGING = 89;
  /** RegularExpression Id. */
  int SET_ESCAPE = 90;
  /** RegularExpression Id. */
  int SET_ESCCHAR = 91;
  /** RegularExpression Id. */
  int SET_EXITCOMMIT = 92;
  /** RegularExpression Id. */
  int SET_FEEDBACK = 93;
  /** RegularExpression Id. */
  int SET_FLAGGER = 94;
  /** RegularExpression Id. */
  int SET_FLUSH = 95;
  /** RegularExpression Id. */
  int SET_HEADING = 96;
  /** RegularExpression Id. */
  int SET_HEADSEP = 97;
  /** RegularExpression Id. */
  int SET_INSTANCE = 98;
  /** RegularExpression Id. */
  int SET_LINESIZE = 99;
  /** RegularExpression Id. */
  int SET_LOBOFFSET = 100;
  /** RegularExpression Id. */
  int SET_LOGSOURCE = 101;
  /** RegularExpression Id. */
  int SET_LONG = 102;
  /** RegularExpression Id. */
  int SET_LONGCHUNKSIZE = 103;
  /** RegularExpression Id. */
  int SET_MARKUP = 104;
  /** RegularExpression Id. */
  int SET_NEWPAGE = 105;
  /** RegularExpression Id. */
  int SET_NULL = 106;
  /** RegularExpression Id. */
  int SET_NUMFORMAT = 107;
  /** RegularExpression Id. */
  int SET_NUMWIDTH = 108;
  /** RegularExpression Id. */
  int SET_OUTPUTFORMAT = 109;
  /** RegularExpression Id. */
  int SET_PAGESIZE = 110;
  /** RegularExpression Id. */
  int SET_PAUSE = 111;
  /** RegularExpression Id. */
  int SET_RECSEP = 112;
  /** RegularExpression Id. */
  int SET_RECSEPCHAR = 113;
  /** RegularExpression Id. */
  int SET_SERVEROUTPUT = 114;
  /** RegularExpression Id. */
  int SET_SHIFTINOUT = 115;
  /** RegularExpression Id. */
  int SET_SHOWMODE = 116;
  /** RegularExpression Id. */
  int SET_SQLBLANKLINES = 117;
  /** RegularExpression Id. */
  int SET_SQLCASE = 118;
  /** RegularExpression Id. */
  int SET_SQLCONTINUE = 119;
  /** RegularExpression Id. */
  int SET_SQLNUMBER = 120;
  /** RegularExpression Id. */
  int SET_SQLPLUSCOMPATIBILITY = 121;
  /** RegularExpression Id. */
  int SET_SQLPREFIX = 122;
  /** RegularExpression Id. */
  int SET_SQLPROMPT = 123;
  /** RegularExpression Id. */
  int SET_SQLTERMINATOR = 124;
  /** RegularExpression Id. */
  int SET_SUFFIX = 125;
  /** RegularExpression Id. */
  int SET_TAB = 126;
  /** RegularExpression Id. */
  int SET_TERMOUT = 127;
  /** RegularExpression Id. */
  int SET_TIME = 128;
  /** RegularExpression Id. */
  int SET_TIMING = 129;
  /** RegularExpression Id. */
  int SET_TRIMOUT = 130;
  /** RegularExpression Id. */
  int SET_TRIMSPOOL = 131;
  /** RegularExpression Id. */
  int SET_UNDERLINE = 132;
  /** RegularExpression Id. */
  int SET_VERIFY = 133;
  /** RegularExpression Id. */
  int SET_WRAP = 134;
  /** RegularExpression Id. */
  int SET_XMLOPTIMIZATIONCHECK = 135;
  /** RegularExpression Id. */
  int SET_XQUERY = 136;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 137;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 138;
  /** RegularExpression Id. */
  int DIGIT = 139;
  /** RegularExpression Id. */
  int IDENTIFIER = 140;
  /** RegularExpression Id. */
  int LETTER = 141;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 142;
  /** RegularExpression Id. */
  int CHAR_LITERAL = 143;
  /** RegularExpression Id. */
  int QUOTED_IDENTIFIER = 144;
  /** RegularExpression Id. */
  int SEMICOLON = 145;
  /** RegularExpression Id. */
  int LINE_COMMENT = 146;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 147;
  /** RegularExpression Id. */
  int ANYTHING = 148;
  /** RegularExpression Id. */
  int NO_SPACE_VALUE = 149;

  /** Lexical state. */
  int IN_NO_SPACE_VALUE = 0;
  /** Lexical state. */
  int IN_SET = 1;
  /** Lexical state. */
  int IN_CLIENT_CMD = 2;
  /** Lexical state. */
  int IN_SQL = 3;
  /** Lexical state. */
  int DEFAULT = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"(\"",
    "\"SELECT\"",
    "\"CALL\"",
    "\"ROLE\"",
    "\"TRANSACTION\"",
    "<NEW_VALUE>",
    "<CMD_NEW_LINE>",
    "\"=\"",
    "\"@\"",
    "\"@@\"",
    "\"/\"",
    "<ACCEPT>",
    "<APPEND>",
    "<ARCHIVE>",
    "<ATTRIBUTE>",
    "<BREAK>",
    "<BTITLE>",
    "<CHANGE>",
    "<CLEAR>",
    "<COLUMN>",
    "<COMPUTE>",
    "<CONNECT>",
    "\"COPY\"",
    "<DEFINE>",
    "<DEL>",
    "<DESCRIBE>",
    "<DISCONNECT>",
    "<EDIT>",
    "<EXECUTE>",
    "<EXIT>",
    "\"GET\"",
    "\"HELP\"",
    "<HOST>",
    "<INPUT>",
    "<LIST>",
    "<PASSWORD>",
    "<PAUSE>",
    "<PRINT>",
    "<PROMPT>",
    "<RECOVER>",
    "<REMARK>",
    "<REPFOOTER>",
    "<REPHEADER>",
    "<RUN>",
    "<SAVE>",
    "\"SET\"",
    "<SHOW>",
    "\"SHUTDOWN\"",
    "<SPOOL>",
    "<START>",
    "<STARTUP>",
    "\"STORE\"",
    "<TIMING>",
    "<TTITLE>",
    "<UNDEFINE>",
    "<VARIABLE>",
    "<WHENEVER>",
    "<XQUERY>",
    "\"CREATE\"",
    "\"DELETE\"",
    "\"DROP\"",
    "\"INSERT\"",
    "\"REPLACE\"",
    "\"TRUNCATE\"",
    "\"UPDATE\"",
    "<SET_APPINFO>",
    "<SET_ARRAYSIZE>",
    "<SET_AUTOCOMMIT>",
    "<SET_AUTOPRINT>",
    "<SET_AUTORECOVERY>",
    "<SET_AUTOTRACE>",
    "<SET_BLOCKTERMINATOR>",
    "<SET_CMDSEP>",
    "\"COLSEP\"",
    "<SET_CONCAT>",
    "<SET_COPYCOMMIT>",
    "\"COPYTYPECHECK\"",
    "<SET_DEFINE>",
    "\"DESCRIBE\"",
    "\"ECHO\"",
    "<SET_EDITFILE>",
    "<SET_EMBEDDED>",
    "<SET_ERRORLOGGING>",
    "<SET_ESCAPE>",
    "\"ESCCHAR\"",
    "<SET_EXITCOMMIT>",
    "<SET_FEEDBACK>",
    "\"FLAGGER\"",
    "<SET_FLUSH>",
    "<SET_HEADING>",
    "<SET_HEADSEP>",
    "\"INSTANCE\"",
    "<SET_LINESIZE>",
    "<SET_LOBOFFSET>",
    "\"LOGSOURCE\"",
    "\"LONG\"",
    "<SET_LONGCHUNKSIZE>",
    "<SET_MARKUP>",
    "<SET_NEWPAGE>",
    "\"NULL\"",
    "<SET_NUMFORMAT>",
    "<SET_NUMWIDTH>",
    "\"OUTPUTFORMAT\"",
    "<SET_PAGESIZE>",
    "<SET_PAUSE>",
    "\"RECSEP\"",
    "\"RECSEPCHAR\"",
    "<SET_SERVEROUTPUT>",
    "<SET_SHIFTINOUT>",
    "<SET_SHOWMODE>",
    "<SET_SQLBLANKLINES>",
    "<SET_SQLCASE>",
    "<SET_SQLCONTINUE>",
    "<SET_SQLNUMBER>",
    "<SET_SQLPLUSCOMPATIBILITY>",
    "<SET_SQLPREFIX>",
    "<SET_SQLPROMPT>",
    "<SET_SQLTERMINATOR>",
    "<SET_SUFFIX>",
    "\"TAB\"",
    "<SET_TERMOUT>",
    "<SET_TIME>",
    "<SET_TIMING>",
    "<SET_TRIMOUT>",
    "<SET_TRIMSPOOL>",
    "<SET_UNDERLINE>",
    "<SET_VERIFY>",
    "<SET_WRAP>",
    "<SET_XMLOPTIMIZATIONCHECK>",
    "\"XQUERY\"",
    "<FLOATING_POINT_LITERAL>",
    "<INTEGER_LITERAL>",
    "<DIGIT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<CHAR_LITERAL>",
    "<QUOTED_IDENTIFIER>",
    "\";\"",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<ANYTHING>",
    "<NO_SPACE_VALUE>",
  };

}
